export enum InjectionTokens {
	USER_REPOSITORY = "USER_REPOSITORY",
	USER_SERVICE = "USER_SERVICE",
	USER_CONTROLLER = "USER_CONTROLLER",

	PATIENT_REPOSITORY = "PATIENT_REPOSITORY",
	PATIENT_SERVICE = "PATIENT_SERVICE",
	PATIENT_CONTROLLER = "PATIENT_CONTROLLER",
}
